services:
  client:
    build: ./client
    ports:
      - "5173:80"
    restart: always
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_URL: ${CLIENT_URL}
      SERVER_URL: ${SERVER_URL}
    env_file:
      - .env.client

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./photos.db:/app/photos.db
    restart: always


volumes:
  uploads:
  db:
