services:
  client:
    build: ./client
    ports:
      - "5173:80"
    restart: always
    environment:
      - ./client/.env

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./photos.db:/app/photos.db
    restart: always
    environment:
      - ./server/.env

volumes:
  uploads:
  db:
