services:
  client:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: always
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      CLIENT_URL: ${CLIENT_URL}

  server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./photos.db:/app/photos.db
    restart: always
    environment:
      SERVER_URL: ${SERVER_URL}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_SESSION_SECRET: ${SERVER_SECRET}
      SERVER_OIDC_ISSUER: ${SERVER_OIDC_ISSUER}
      SERVER_OIDC_CLIENT_ID: ${SERVER_OIDC_CLIENT_ID}
      SERVER_OIDC_CLIENT_SECRET: ${SERVER_OIDC_CLIENT_SECRET}


volumes:
  uploads:
  db:
